<?php
/** @var $this /Magento/Framework/View/Element/Template */
/** @var $viewModel /NetBytes/LogsExplorer/ViewModel/LogsTree */
$viewModel = $this->getViewModel();
$tree = $viewModel->getTree();
?>
<div class="logs-management">
    <table class="data-grid" data-role="data-grid">
        <thead>
        <tr>
            <th class="data-grid-th no-link"><?= __('Directory Tree') ?></th>
            <th class="data-grid-th no-link"><?= __('Content') ?></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td class="data-grid-td">
                <div class="logs-tree" id="directory-tree"
                     data-mage-init='{
                             "logs-tree": {
                                "treeData": <?= $tree ?>
                             }
                         }'>
                </div>
            </td>
            <td class="data-grid-td">
                <pre id="log-content">
                    <?= __('Please select a file to view') ?>
                </pre>
            </td>
        </tr>
        </tbody>
    </table>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "content-view" : {
                "baseUrl": "<?= $this->getUrl('logs/logs/view') ?>"
            }
        }
    }
</script>

