<?php
/** @var Magento\Framework\View\Element\Template $this */
$viewModel = $this->getViewModel();
/** @var NetBytes\LogsManagement\ViewModel\LogsTree $viewModel */
$tree = $viewModel->getTree();
?>
<div class="logs-management">
    <table class="data-grid" data-role="data-grid">
        <thead>
        <tr>
            <th class="data-grid-th no-link"><?= __('Directory Tree') ?></th>
            <th class="data-grid-th no-link"><?= __('Content') ?></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td class="data-grid-td">
                <div class="logs-tree" id="directory-tree"
                     data-mage-init='{
                             "logs-tree": {
                                "treeData": <?= $tree ?>
                             }
                         }'>
                </div>
            </td>
            <td class="data-grid-td">
                <div class="note">
                    <span><?= __('Select a file in the directory tree on the left to view its contents.') ?></span>
                </div>
                <pre id="log-content">
                </pre>
            </td>
        </tr>
        </tbody>
    </table>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "content-view" : {
                "baseUrl": "<?= $this->getUrl('logs/logs/view') ?>"
            }
        }
    }
</script>

